- SpeechDetection/saisandhya01/README.md
- SpeechDetection/saisandhya01/index.html
- SpeechDetection/saisandhya01/script.js
- SpeechDetection/saisandhya01/styles.css
Hi @thinkswell, this is the new PR. This is with respect to issue #4 
Do check if everything is okay.
Thank you
> Added SpeechDetection App

- RandomQuote/marianaruddy/app.js
- RandomQuote/marianaruddy/index.html
- RandomQuote/marianaruddy/style.css
> add quote generator project

- randomPassword/sebabratakundu/app.js
- randomPassword/sebabratakundu/index.html
- randomPassword/sebabratakundu/style.css
Objective : 
To create a beautiful website for a random password generator.
Process : 
created a template using HTML, CSS, and bootstrap and set random background image using Unsplash.com.
use javascript to generate a random password according to how many character password I want.
shows error msg if the number of digits == 0.
> add a random password generator project using java script, html, bootstrap

- Clock/rashis17/README.md
- Clock/rashis17/analogApp.js
- Clock/rashis17/analogClock.html
- Clock/rashis17/digitalApp.js
- Clock/rashis17/digitalClock.html
- Clock/rashis17/styles.css
In reference to issue #1 Clock
> Added digital/analog clock

- RandomQuote/marianaruddy/app.js
- RandomQuote/marianaruddy/index.html
- RandomQuote/marianaruddy/style.css
modifications:
- adjust font
- rearrange items layout
- add random B&W background image
> improve style

- randomPassword/camiloibarrayepes/index.html
- randomPassword/camiloibarrayepes/readme.md
readme added
wrong word changed
> readme added

- randomPassword/WulfPlasma/Script.js
- randomPassword/WulfPlasma/index.html
- randomPassword/WulfPlasma/js/Main.js
- randomPassword/WulfPlasma/styles.css
> Simple JavaScript Random Password Generator

- .gitignore
- Clock/hoanglm-1051/app.js
- Clock/hoanglm-1051/index.html
- Clock/hoanglm-1051/style.css
This pull request for basic clock is linked to issue #1, please check it @thinkswell :D
> Contribute Clock to javascript-mini-projects

- .gitignore
- MiniPaint/hoanglm-1051/app.js
- MiniPaint/hoanglm-1051/index.html
- MiniPaint/hoanglm-1051/style.css
This pull request for Mini Paint App is linked to issue #3, please check it @thinkswell :D
> Contribute Mini Paint App to javascript-mini-projects

- NumberGuessing/mihinduranasinghe/app.js
- NumberGuessing/mihinduranasinghe/index.html
Added a Number Guessing game mini project in javascript
> Added a Number Guessing game mini project 

- randomPassword/iamsahebgiri/app.js
- randomPassword/iamsahebgiri/index.html
- randomPassword/iamsahebgiri/style.css
This can randomly generate Password (Pseudo random).
Can directly copy to the clipboard
> added random password generator - lastpass

- TaskListManager/mihinduranasinghe/app.js
- TaskListManager/mihinduranasinghe/index.html
Task List Manager mini project stable version. 
Features - Add , delete and filter tasks in a task list. Local storage is used to keep and track records of each
> Task List Manager mini project stable version.

- ProfileScroller/mihinduranasinghe/app.js
- ProfileScroller/mihinduranasinghe/index.html
Bio Profiles Scroller with a button.
- Profile details are set in an object array and they will be iterated
> Bio Profiles Scroller with a button.

- UpCounter/harshv9988/index.html
- UpCounter/harshv9988/script.js
- UpCounter/harshv9988/style.css
Added a javascript upcounter mini project
> UpCounter s project added

- ColorChangingCircle/lapohjan/index.html
- ColorChangingCircle/lapohjan/script.js
- ColorChangingCircle/lapohjan/style.css
> add html css and js

- Clock/marianaruddy/app.js
- Clock/marianaruddy/index.html
- Clock/marianaruddy/style.css
> add clock project

- RandomQuote/coolpulkit99/index.html
- RandomQuote/coolpulkit99/logic.js
- RandomQuote/coolpulkit99/readme.md
- RandomQuote/coolpulkit99/styles.css
A minimal Random Quote generator project built using vanilla JS without any library.
Issue #13
> Added project for 'RandomQuote'

- CountDownTimer/coolpulkit99/index.html
- CountDownTimer/coolpulkit99/logic.js
- CountDownTimer/coolpulkit99/readme.md
- CountDownTimer/coolpulkit99/style.css
A simple countdown timer which takes user input in seconds. Made using Vanilla JS without any external library.
A variation of #5 which takes user input for time instead of a fixed time.
> Added project for 'Countdown Timer'

- Typing Game/kuwarbir/css/style.css
- Typing Game/kuwarbir/index.html
- Typing Game/kuwarbir/js/app.js
Typing speed game in which you are given random words. You select difficulty level and you have to type the word in the time given. timer will be running according to difficulty level
> Added typing speed game project

- randomPassword/headstylecolorred/.vscode/settings.json
- randomPassword/headstylecolorred/index.html
- randomPassword/headstylecolorred/main.js
- randomPassword/headstylecolorred/styles.css
This is a pull request to include a new password generator to this javascript project :D
> Created random password generator

- randomPassword/sebabratakundu/index.html
- randomPassword/sebabratakundu/style.css
**Note:** code for functionality (javascript) has not been alerted and maintains its purpose. Only design was updated
- generate button has new width, height, and colors (includes on hover)
- card title's font size is smaller with centered aligning 
- Height and width for the card has been changed
- Width for form is much smaller
> UI improvements

- VelocityCalc/deepharshsri/.vscode/settings.json
- VelocityCalc/ritikakhandelwal-17/index.html
- VelocityCalc/ritikakhandelwal-17/index.js
- VelocityCalc/ritikakhandelwal-17/style.css
It is a responsive web page that can calculate initial velocity , final velocity , time or acceleration , given values of any three of them are provided.
> velocity calculator 

- RandomQuote/mnk17arts/index.html
- RandomQuote/mnk17arts/mnk17arts'-Quote-machine.json
- RandomQuote/mnk17arts/scripts/index.js
- RandomQuote/mnk17arts/styles/index.css
> Random Quote Machine

- Rateit/Deep1Shikha/app.js
- Rateit/Deep1Shikha/index.html
- Rateit/Deep1Shikha/style.css
Rating feature is implemented.
Rated value is shown below the icons.
> Rate it added

- ExpandingCards/robertnjenga/index.html
- ExpandingCards/robertnjenga/index.js
- ExpandingCards/robertnjenga/style.css
> Added Expanding Cards mini project

- StickyNotes/dasgupta002/main.html
- StickyNotes/dasgupta002/sticky.css
> Sticky notes widget which can hold entered data using local storage.

- ToDoList/OmPr366/index.html
- ToDoList/OmPr366/script.js
- ToDoList/OmPr366/style.css
- randomPassword/OmPr366/index.css
- randomPassword/OmPr366/index.html
- randomPassword/OmPr366/index.js
> Random Pass Generator

- CookingMeasurements/mandy6720/index.css
- CookingMeasurements/mandy6720/index.html
- CookingMeasurements/mandy6720/index.js
Adds a cooking measurement conversion calculator
> Adds project!

- CountDownTimer/OmPr366/index.html
- CountDownTimer/OmPr366/index.js
- CountDownTimer/OmPr366/style.css
> CountDownTimer

- randomPassword/SoniArpit/index.html
- randomPassword/SoniArpit/main.js
Simple random password generator,
Features
-------------
- User can decide the length of the password
- Include/Exclude uppercase letters
- Include/Exclude lowercase letters
- Include/Exclude numbers
- Include/Exclude symbols
- Copy to clipboard
[Screenshot]
> Password generator 

- Notes_APP_NodeJS/shyam640/1.0_Notes_app.js
- Notes_APP_NodeJS/shyam640/1.1_Notes_app.js
- Notes_APP_NodeJS/shyam640/README.md
- Notes_APP_NodeJS/shyam640/notes.json
- Notes_APP_NodeJS/shyam640/package.json
**Refer <a href="https://github.com/shyam640/javascript-mini-projects/blob/master/Notes_APP_NodeJS/shyam640/README.md">Readme</a> file for more details**
- **``` Adding a note ```** : ``` node 1.0_Notes_app.js add --title="Note1" --body="This is note1"  ```
- **``` Removing a note ```** : ``` node 1.0_Notes_app.js remove --title="Task4"  ```
- **``` Listing all notes title ```** : ``` node 1.0_Notes_app.js list  ```
- **``` Reading a note body ```** : ``` node 1.0_Notes_app.js read --title="Note1"  ```
<br>
<br>
> Added Notes App with NodeJS

- BlackJack/kavisherlock/README.md
- BlackJack/kavisherlock/index.html
- BlackJack/kavisherlock/script.js
- BlackJack/kavisherlock/style.css
> Added a single-player game of blackjack

- NumberSeparator/masihbr/index.html
- NumberSeparator/masihbr/main.js
- NumberSeparator/masihbr/readme.md
Simple number separator js code with bootstrap html page for my first pull request.
> Number separator

- WeatherApp/Tushar-2003/index.html
- WeatherApp/Tushar-2003/index.js
- WeatherApp/Tushar-2003/readme.md
- WeatherApp/Tushar-2003/style.css
- used a gradient for the background.
- simple design.
- it is a working project.
> added a weather app

- Minesweeper/vanshuhassija/README.md
- Minesweeper/vanshuhassija/index.html
- Minesweeper/vanshuhassija/js/index.js
- Minesweeper/vanshuhassija/style/index.css
This project is a javascript based game. It allows you to click a cell from 9*9 grid. It shows the number of bombs placed in the surrounding. If a bomb is clicked at any point, game gets over and you are asked to play again.
https://user-images.githubusercontent.com/33016642/194121930-dcdfc693-ae7c-448e-8010-ae631e556365.mov
> Minesweeper JS Game

- ToDoList/mukesh/index.html
- ToDoList/mukesh/index.js
- ToDoList/mukesh/style.css
> add todo list

- NumberGuess/Asher-JH/Readme.md
- NumberGuess/Asher-JH/index.html
- NumberGuess/Asher-JH/index.js
- NumberGuess/Asher-JH/styles.css
Number guessing game - AsherJH
Hoping I can get the Hacktoberfest tag added to it too 😉
> Number Guessing Game

- Fibonacci/mvpsdvlpr/README.md
- Fibonacci/mvpsdvlpr/package-lock.json
- Fibonacci/mvpsdvlpr/package.json
- Fibonacci/mvpsdvlpr/src/main.js
> Fibonacci mvpsdvlpr

- TicTacToeGame/samuelsimoes31/index.html
- TicTacToeGame/samuelsimoes31/script.js
- TicTacToeGame/samuelsimoes31/styles.css
> Simple tic tac toe game

- Calculator/sushil-2803/index.html
- Calculator/sushil-2803/style.css
- Calculator/sushil-2803/use.js
@thinkswell please approve 
A simple js calculator
> simple calculator in js

- Calculator/sushil-2803/index.html
- Calculator/sushil-2803/style.css
- Calculator/sushil-2803/use.js
- tipcalculator/sushil-2803/index.html
- tipcalculator/sushil-2803/tip.css
- tipcalculator/sushil-2803/tip.js
Calucalate tip on basis of percentage
@thinkswell  please approve
> Tip calculator sushil 2803

- GenerativeArt/code4Y/README.md
- GenerativeArt/code4Y/index.html
- GenerativeArt/code4Y/script.js
- GenerativeArt/code4Y/style.css
This is a JavaScript project to celebrate Diwali festival in Digital manner using Generative Art for creating Rangoli.
<p align="center">
</p>
Thank you!
> Generative Art Project :white_flower: 

- MouseHover/shivamdangi7/index.html
- MouseHover/shivamdangi7/script.js
- MouseHover/shivamdangi7/style.css
Hey Corrected and pushed @thinkswell  
https://shivamdangi7.github.io/MouseHover/
Added my contribution a small js based kinda game.
> Added MouseHover project 

- ColorSchemePicker/QuangLyHo/index.html
- ColorSchemePicker/QuangLyHo/index.js
- ColorSchemePicker/QuangLyHo/style.css
> QuangLyHo added color scheme picker project

- README.md
This pull request adds several subsections to the documentation, including a description, usage, what you can contribute, and how you can contribute sections.
> Update README.md: Added info regarding description, usage, and contributions

- Clock/beginner1986/index.html
- Clock/beginner1986/script.js
- Clock/beginner1986/style.css
> Clock beginner1986

- WeatherApp/frozenchicken/index.html
- WeatherApp/frozenchicken/style.css
- WordCrusher/sanyam2301/index.html
> frozenchicken

- MadStory/hritikbhattacharya/index.html
- MadStory/hritikbhattacharya/script.js
- MadStory/hritikbhattacharya/style.css
issue number : #571 
Screen shot:
Live linl:
https://hritikbhattacharya.github.io/Madlibs/
Note:
All the provided features are added , except the multiple story template .
That feature will added in next PR.
> MasStory app added

- CutomVideoControl/Vishal2002/index.html
- CutomVideoControl/Vishal2002/script.js
- CutomVideoControl/Vishal2002/style.css
> I have contributed in the Custom Video Controller under Hacktoberfest 2023

- RandomQuote/AckermanLevi1/index.css
- RandomQuote/AckermanLevi1/index.html
- RandomQuote/AckermanLevi1/index.js
> Random Quote Generator Added

- VectorRunner/JatayuIPv4/index.html
- VectorRunner/JatayuIPv4/sketch.js
- VectorRunner/JatayuIPv4/styles.css
Vector Runner is a generic infinite runner game like Chrome Dino, but with better physics and effects. Used sketch.js for the canvas. Help the square block jump the platforms and complete its never ending destination.
> Vector Runner Game

- BallColoron/TidePlus/index.html
- BallColoron/TidePlus/main.js
- BallColoron/TidePlus/style.css
Created a mini game called "Ball Coloron" where you have to match the color of the bars with the ball. The bouncing ball
changes color after each bar. Tap on the bar to switch the colors (Red, Yellow, Purple) and always match the ball and bar colors
> Ball Coloron Game

- SimpleCalculator/Shiva-Sai-ssb/index.html
- SimpleCalculator/Shiva-Sai-ssb/myscript.js
- SimpleCalculator/Shiva-Sai-ssb/style.css
I have added Calculator project.
> chore: Add Calculator Project

- VoiceGenerator/Sahil-K123/index.html
- VoiceGenerator/Sahil-K123/script.js
- VoiceGenerator/Sahil-K123/style.css
This Voice Generator app provides the different voices from the various voices providing according to the region.
[###### _add a working project link here_](http://127.0.0.1:5500/javascript-mini-projects/VoiceGenerator/Sahil-K123/index.html)
-#714
> feat: Adding Voice Generator App

- JokeGenerator/AckermanLevi1/index.css
- JokeGenerator/AckermanLevi1/index.html
- JokeGenerator/AckermanLevi1/index.js
> Joke Generator Added

- Calculator/sushil-2803/style.css
- [ ✔] Followed guidelines mentioned in the readme file.
- [ ✔] Followed directory structure. (e.g. ProjectName/{USERNAME}/...yourfiles)
- [ ✔] Starred ⭐ the Repo (Optional)
Updated the Calculator UI improved.
> Enhanced Calculator

- Calculator/saikrishna823/calculator.js
- Calculator/saikrishna823/index.html
- Calculator/saikrishna823/styles.css
> Completed Adding Calculator App

- README.md
> Added badge and code snippet to the Readme

- RockPaperScissorsGame/vinay-s36/READme.md
- RockPaperScissorsGame/vinay-s36/index.html
- RockPaperScissorsGame/vinay-s36/script.js
- RockPaperScissorsGame/vinay-s36/style.css
✅Followed guidelines mentioned in the readme file.
✅Followed directory structure. (e.g. ProjectName/{USERNAME}/...yourfiles)
✅Starred ⭐ the Repo (Optional)
> Snake-Water-Gun project

- CurrencyConverter/Tushar2930/index.html
- CurrencyConverter/Tushar2930/readme.md
- CurrencyConverter/Tushar2930/script.js
- CurrencyConverter/Tushar2930/styles.css
> Currency converter #877

- NetworkStatusTracker/ShaikhAman01/app.js
- NetworkStatusTracker/ShaikhAman01/index.html
- NetworkStatusTracker/ShaikhAman01/styles.css
The "Network Status Tracker" project is a web application that allows users to monitor their network status. It provides real-time feedback on the network connection, displaying a green indicator when the network is online and a red indicator when the network is offline. Users can see their network status at a glance and receive notifications when the network connection is lost or restored.
https://shaikhaman01.github.io/NetworkStatusTracker/
> Added NetworkStatus Tracker

- NoteTakingApp/malivinayak/index.html
- NoteTakingApp/malivinayak/script.js
- NoteTakingApp/malivinayak/styles.css
Following features are provided
- You can add simple note title and description
- You can edit Note
- You can delete Note
> Projet : NoteTakingApp

- README.md
To implement PascalCase, to name the committed directory.
> update: PascalCase necessity

- README.md
- Added Icons wherever necessary.
- Made the typos better.
- Improved the structure of the README.md file.
- Made it clear, concise, precise and to the point.
- Added more information on writing README.md for the project.
> update, fix: Improving and fixing the README.md

- KeyPrinter/kohi9noor/index.html
- KeyPrinter/kohi9noor/script.js
- KeyPrinter/kohi9noor/style.css
> Added KeyPrinter project

- README.md
add: Maintainer
add: Contributor
add: README.md section tag: 'Important' updated.
> update: maintainer, contributor, README.md section.

- README.md
> update: Typos remove.

- QuizApp/bhatiaarpit/index.html
- QuizApp/bhatiaarpit/script.js
- QuizApp/bhatiaarpit/style.css
It is a simple QuizApp created with the help of HTMl, CSS and JS
https://github.com/thinkswell/javascript-mini-projects/assets/118626392/19031b77-2b36-4b10-84d9-13028f659e0c
> Quiz-App By bhatiaarpit

- Clock/Itzanway/clock.css
- Clock/Itzanway/clock.html
- Clock/Itzanway/clock.js
> animation clock added

- CountDownTimer/Jagm33t/index.html
- CountDownTimer/Jagm33t/index.js
- CountDownTimer/Jagm33t/readme.md
- CountDownTimer/Jagm33t/style.css
######This project is a simple countdown timer with start, stop, and reset features. It's designed for easy time tracking, suitable for events or personal use. The timer is user-friendly, allowing anyone to manage time efficiently.
> Countdown added

- MusicPlayerApp/app.js
- MusicPlayerApp/index.html
- MusicPlayerApp/style.css
Objective:
Contributed to an open-source project by creating a MusicPlayer app with features like play, pause, next, and previous functionality.
Project Structure:
Organized the project into separate HTML, CSS, and JavaScript files for better maintainability.
Included an "assets" folder to store music files and images.
JavaScript Functionality:
Implemented play, pause, next, and previous functionality using JavaScript.
Added a seek bar to allow users to skip to specific parts of the music.
Displayed the current time and total duration of the song.
Testing:
Future Enhancements (if applicable):
Can explore additional features like volume control, playlist support, and more.
Considered adding animation or transitions for a smoother user experience.
and also enhance proper and beautifull UI …
> feat:Add a MusicPlayer app #812

- RandomQuote/MaxBR97/index.html
- RandomQuote/MaxBR97/index.js
> Random Quote Generator/ MaxBR97

- SimonGame/mukherjee16swastika/README.md
- SimonGame/mukherjee16swastika/SimonSays.css
- SimonGame/mukherjee16swastika/SimonSays.html
- SimonGame/mukherjee16swastika/SimonSays.js
> My first commit

- BMICalculator/premgajare/index.html
- BMICalculator/premgajare/script.js
- BMICalculator/premgajare/style.css
- CurrencyConverter/premgajare/index.html
- CurrencyConverter/premgajare/script.js
- CurrencyConverter/premgajare/style.css
Developer Checklist
Summary
Since there is no folder for BMICalculator , I added the folder with three files in it.
A simple web app with a basic UI has been made.
Screenshot
> BMI Calculator files added

- CodeSnippetsChromeExtension/index.html
- CodeSnippetsChromeExtension/styles.css
- DynamicQuotesGenerator/VidhiShiste/index.html
- DynamicQuotesGenerator/VidhiShiste/script.js
- DynamicQuotesGenerator/VidhiShiste/style.css
Since there was no folder for DynamicQuotesGenerator I added the folder with three files in it 
A simple app with a basic UI has been made
> basic app UI added

- SudokuGame/index.html
- SudokuGame/script.js
- SudokuGame/style.css
Fixes #869 
Created a Sudoku game using HTML, CSS and JS.
Hope this solves the issue.
Looking forward for merging this PR.
Created a sudoku game using HTML, CSS and JavaScript. Works completely fine.
https://github.com/thinkswell/javascript-mini-projects/assets/143169520/c268985d-25ea-48d8-9230-554afda018eb
> sudoku_game/DevanshKyada27

- .replit
- index .html
- package-lock.json
- package.json
- ping-pong-game/ping.html
- pingpong.html
- random_color_generator/color.java
- script.js
- style.css
- sudokogame/index.html
- sudokogame/script.js
- sudokogame/style.css
fixes-#869 
- [ X] Followed guidelines mentioned in the readme file.
- [ X] Followed directory structure. (e.g. ProjectName/{USERNAME}/...yourfiles)
- [ X] Starred ⭐ the Repo (Optional)
Created a Sudoku Game using HTML, CSS and JavaScript. Works completely fine.
> created a sudoko game using html css and javascript

- Background_Colour_Switcher/index.html
- Background_Colour_Switcher/script.js
> Background colour switcher added

- colorful console pattern.js
> colorful console

- Currency Converter/index.html
- Currency Converter/script.js
- Currency Converter/style.css
Fixes #266 
Created a currency convertor using HTML, CSS and JavaScript.
> Created a currency convertor

- breakout/index.html
- breakout/index.js
- breakout/styles.css
> added breakout game

- Sudoku/parag477/index.html
- Sudoku/parag477/script.js
- Sudoku/parag477/style.css
Closes #869 
- [*] Followed guidelines mentioned in the readme file.
- [*] Followed directory structure. (e.g. ProjectName/{USERNAME}/...yourfiles)
- [*] Starred ⭐ the Repo (Optional)
> Added sudoku game

- BirdFlap/daulatojha17/index.html
- BirdFlap/daulatojha17/readme.md
- BirdFlap/daulatojha17/script.js
- BirdFlap/daulatojha17/style.css
A simple bird game in JavaScript involves using HTML5 Canvas for rendering and JavaScript for game logic. In this game, you'll control a bird that can flap its wings and avoid obstacles. Below is a basic implementation of a simple bird game
> FlappyBird mini js project

- Calculator/parthasdey2304/calculator.html
Added a new calculator with history feature!!!
> Create calculator.html issue #626

- Love Calculator/index.html
- Love Calculator/readme.md
- Love Calculator/script.js
- Love Calculator/style.css
t's a Love Calculator where Users have to put his/her name with partner's name and the calculator calculates the Love percentage randomly between them and display
> Love Calculator added

- QuizApp/Vivek-GuptaXCode/index.css
- QuizApp/Vivek-GuptaXCode/index.html
- QuizApp/Vivek-GuptaXCode/index.js
- QuizApp/Vivek-GuptaXCode/questions.json
- SpeedTypingTest/Vivek-GuptaXCode/app.js
- SpeedTypingTest/Vivek-GuptaXCode/index.css
- SpeedTypingTest/Vivek-GuptaXCode/index.html
Speed Tying Test with Words per minutes and Accuracy parameter and a great UI.
> Speed Typing Test

- QuizApp/Vivek-GuptaXCode/index.css
- QuizApp/Vivek-GuptaXCode/index.html
- QuizApp/Vivek-GuptaXCode/index.js
- QuizApp/Vivek-GuptaXCode/questions.json
A quiz app with timer of 10 second with a ton of questions and nice UI.
> Added Quiz App with Timer.

- PianoApp/sanathan-git/index.html
- PianoApp/sanathan-git/main.js
- PianoApp/sanathan-git/style.css
- [ [✔️](https://emojipedia.org/check-mark)] Followed guidelines mentioned in the readme file.
- [[✔️](https://emojipedia.org/check-mark) ] Followed directory structure. (e.g. ProjectName/{USERNAME}/...yourfiles)
- [[✔️](https://emojipedia.org/check-mark) ] Starred ⭐ the Repo (Optional)
Made piano app using html,css,js 
Enhanced UI , user friendly interface
> piano app using Js

- JokeGenerator/yashwanthvarma18/index.html
- JokeGenerator/yashwanthvarma18/script.js
- JokeGenerator/yashwanthvarma18/style.css
I have created a Random Joke Generator app using HTML, CSS, and JavaScript. The app features a user-friendly interface with a button to fetch random jokes and display them in a fixed-size container. The jokes are fetched from an external API and are displayed with a smooth typing animation. The button also has a subtle scale-up animation on hover. The app follows proper styling and user experience guidelines, and the code is organized into separate HTML, CSS, and JavaScript files.
> Random Joke Generator-yashwanthvarma18

- SortingVisualizer/protocol-weaver/index.html
- SortingVisualizer/protocol-weaver/readme.md
- SortingVisualizer/protocol-weaver/script.js
- SortingVisualizer/protocol-weaver/style.css
The Sorting Visualizer is a basic web application that allows you to visualize the process of sorting  on a set of randomly generated bars.
HTML
CSS
JavaScript
> SortingVisualizer

- color changer mini app#1115/index.html
- color changer mini app#1115/script.js
- color changer mini app#1115/styles.css
The Color Changer Mini-App is a delightful and interactive JavaScript application that allows users to infuse life and personality into web elements by changing colors. This fun project goes beyond the conventional background color shift, offering a versatile palette of possibilities – from buttons to text, images, and even animations.
1. Selective Element Coloring:
- Users can handpick individual elements on the webpage and breathe new colors into them.
2. Color Palette Flexibility:
- A pre-defined palette of colors and the ability to input custom color codes (hex, RGB, etc.) give users the freedom to choose.
3. Real-time Dynamic Color Changes:
- Witness the magic as the selected element transforms its color dynamically in real time.
4. User-friendly Interface:
- The app boasts an …
> Created a Color Changer Mini-App

- Library/worm29/books.js
- Library/worm29/index.css
- Library/worm29/index.html
> Library App to add your favorite books

- 1Application-frontend/ToDoApp/vanessanserrano/index.html
- 1Application-frontend/ToDoApp/vanessanserrano/script.js
- 1Application-frontend/ToDoApp/vanessanserrano/style.css
- [ ✓] Followed guidelines mentioned in the readme file.
- [ ✓] Followed directory structure. (e.g. ProjectName/{USERNAME}/...yourfiles)
To Do List that allows a user to add tasks, delete tasks, and mark tasks completed.
> Added To-Do List project with add, delete, and mark completed features

- QuizApp/hanzalakhan010/data/db.json
- QuizApp/hanzalakhan010/index.html
- QuizApp/hanzalakhan010/script.js
- QuizApp/hanzalakhan010/script2.js
- QuizApp/hanzalakhan010/styles.css
- [Done  ] Followed guidelines mentioned in the readme file.
- [ Done ] Followed directory structure. (e.g. ProjectName/{USERNAME}/...yourfiles)
- [Doing it in a second ] Starred ⭐ the Repo (Optional)
This quiz app consists of many features such as selecting quiz type,difficulty level,
- it also has timer which closes quiz if time exceeds 
- score board (based on local storage)
> Added QuizApp by hanzala khan010
